// projects/wujie-demo/packages/sub-react/src/App.tsx
import { Routes, Route, useNavigate, useLocation } from 'react-router-dom'
import { useState, useEffect, useCallback } from 'react'
import Overview from './pages/Overview'
import Detail from './pages/Detail'

function App() {
  const navigate = useNavigate()
  const location = useLocation()
  const [receivedMessages, setReceivedMessages] = useState<{ from: string; content: string }[]>([])
  const [commMessage, setCommMessage] = useState('')

  // 读取插件注入的配置
  const appConfig = (window as any).APP_CONFIG || null
  const propsInfo = (window as any).$wujie?.props || null

  // 监听 eventBus 消息 + 导航询问
  useEffect(() => {
    const bus = (window as any).$wujie?.bus
    if (!bus) return

    const handler = (data: { from: string; message: string }) => {
      setReceivedMessages(prev => [{ from: data.from, content: data.message }, ...prev])
    }

    // 监听主应用的导航询问，始终允许切换
    const navHandler = (data: { requestId: string; subAppName: string; targetPath: string }) => {
      // 只响应发给自己的询问
      const myName = (window as any).__WUJIE?.id
      if (data.subAppName && myName && data.subAppName !== myName) return

      console.log('%c[sub-react] 收到导航询问，允许切换', 'color: #52c41a; font-weight: bold;')
      bus.$emit('navigationResponse', {
        requestId: data.requestId,
        allowed: true
      })
    }

    bus.$on('subMessage', handler)
    bus.$on('requestNavigation', navHandler)
    return () => {
      bus.$off('subMessage', handler)
      bus.$off('requestNavigation', navHandler)
    }
  }, [])

  const sendMessage = useCallback(() => {
    if (!commMessage.trim()) return
    const bus = (window as any).$wujie?.bus
    if (bus) {
      bus.$emit('subMessage', { from: 'sub-react', message: commMessage })
      setCommMessage('')
    }
  }, [commMessage])

  return (
    <div className="app-container">
      <div className="app-header">
        <span className="app-title">数据仪表盘</span>
        <span className="app-badge">sub-react | React</span>
      </div>

      {/* Props 信息 */}
      {propsInfo && (
        <div style={{
          marginBottom: 16, padding: '10px 14px', background: '#e6f7ff',
          border: '1px solid #91d5ff', borderRadius: 6, fontSize: 13, color: '#1890ff'
        }}>
          <strong>Props 通信:</strong> 模式: {propsInfo.mode} | 用户: {propsInfo.userInfo?.name}
        </div>
      )}

      {/* 导航 */}
      <div className="nav-tabs">
        <div
          className={`nav-tab ${location.pathname === '/' ? 'active' : ''}`}
          onClick={() => navigate('/')}
        >
          概览
        </div>
        <div
          className={`nav-tab ${location.pathname === '/detail' ? 'active' : ''}`}
          onClick={() => navigate('/detail')}
        >
          详情
        </div>
      </div>

      <Routes>
        <Route path="/" element={<Overview />} />
        <Route path="/detail" element={<Detail />} />
      </Routes>

      {/* 插件信息面板 */}
      <div className="plugin-panel">
        <h4>插件系统 (jsBeforeLoaders)</h4>
        <div style={{ fontSize: 12, color: '#666', marginBottom: 8 }}>
          以下配置由主应用通过插件在子应用加载前注入到 window.APP_CONFIG:
        </div>
        <div className="plugin-config">
          {appConfig ? JSON.stringify(appConfig, null, 2) : '未在微前端环境中 (独立运行时不注入)'}
        </div>
      </div>

      {/* 通信面板 */}
      <div className="comm-panel">
        <h4>eventBus 通信</h4>
        <div className="comm-input-group">
          <input
            className="comm-input"
            value={commMessage}
            onChange={e => setCommMessage(e.target.value)}
            placeholder="输入要发送的消息..."
            onKeyDown={e => e.key === 'Enter' && sendMessage()}
          />
          <button className="comm-btn" onClick={sendMessage}>发送</button>
        </div>
        <div className="comm-log">
          {receivedMessages.length === 0 ? (
            <div style={{ color: '#999' }}>等待接收消息...</div>
          ) : (
            receivedMessages.map((msg, i) => (
              <div key={i} style={{ padding: '2px 0' }}>
                [{msg.from}] {msg.content}
              </div>
            ))
          )}
        </div>
      </div>
    </div>
  )
}

export default App

// projects/wujie-demo/packages/sub-vue/src/App.vue
<template>
  <div class="app-container">
    <div class="app-header">
      <span class="app-title">待办事项</span>
      <span class="app-badge">sub-vue | Vue3</span>
    </div>

    <!-- Props 信息展示 -->
    <div class="props-info" v-if="propsInfo">
      <strong>Props 通信:</strong> 用户: {{ propsInfo.userInfo?.name }} | 角色: {{ propsInfo.userInfo?.role }}
    </div>

    <!-- 导航切换保护提示 -->
    <div
      v-if="pendingTodos.length > 0"
      style="margin-bottom: 12px; padding: 10px 14px; background: #fff7e6; border: 1px solid #ffd591; border-radius: 6px; font-size: 13px; color: #fa8c16;"
    >
      ⚠️ 当前有 {{ pendingTodos.length }} 个未完成待办，主应用切换菜单时会先询问确认。
    </div>

    <!-- 导航 -->
    <div class="nav-tabs">
      <div
        class="nav-tab"
        :class="{ active: $route.path === '/' }"
        @click="$router.push('/')"
      >
        列表
      </div>
      <div
        class="nav-tab"
        :class="{ active: $route.path === '/stats' }"
        @click="$router.push('/stats')"
      >
        统计
      </div>
    </div>

    <router-view :todos="todos" @add-todo="addTodo" @toggle-todo="toggleTodo" @remove-todo="removeTodo" />

    <!-- 通信面板 -->
    <div class="comm-panel">
      <h4>eventBus 通信</h4>
      <div style="display: flex; gap: 8px; margin-bottom: 8px;">
        <input class="todo-input" v-model="commMessage" placeholder="输入要发送的消息..." />
        <button class="btn btn-info btn-small" @click="sendMessage">发送给其他应用</button>
      </div>
      <div class="comm-log">
        <div v-if="receivedMessages.length === 0" style="color: #999;">等待接收消息...</div>
        <div v-for="(msg, i) in receivedMessages" :key="i" style="padding: 2px 0;">
          [{{ msg.from }}] {{ msg.content }}
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, computed, onMounted, onUnmounted } from 'vue'

interface Todo {
  id: number
  text: string
  done: boolean
}

const todos = reactive<Todo[]>([
  { id: 1, text: '学习无界微前端框架', done: true },
  { id: 2, text: '搭建主应用项目', done: true },
  { id: 3, text: '配置子应用路由同步', done: false }
])

let nextId = 4

// 获取 props
const propsInfo = (window as any).$wujie?.props || null

// ========== 待办事项操作 ==========
function addTodo(text: string) {
  todos.push({ id: nextId++, text, done: false })
}

function toggleTodo(id: number) {
  const todo = todos.find(t => t.id === id)
  if (todo) todo.done = !todo.done
}

function removeTodo(id: number) {
  const index = todos.findIndex(t => t.id === id)
  if (index !== -1) todos.splice(index, 1)
}

// ========== 导航切换保护 ==========
const pendingTodos = computed(() => todos.filter(t => !t.done))

/**
 * 监听主应用的导航询问
 * 如果有未完成的待办事项，拒绝切换并说明原因
 */
function handleNavigationRequest(data: { requestId: string; subAppName: string; targetPath: string }) {
  const bus = (window as any).$wujie?.bus
  if (!bus) return

  // 只响应发给自己的询问（保活状态下其他子应用也可能收到广播）
  const myName = (window as any).__WUJIE?.id
  if (data.subAppName && myName && data.subAppName !== myName) return

  const unfinished = todos.filter(t => !t.done)
  if (unfinished.length > 0) {
    console.log(`%c[sub-vue] 收到导航询问，有 ${unfinished.length} 个未完成待办，拒绝切换`, 'color: #fa8c16; font-weight: bold;')
    bus.$emit('navigationResponse', {
      requestId: data.requestId,
      allowed: false,
      reason: `当前有 ${unfinished.length} 个待办事项未完成，请先处理后再切换`
    })
  } else {
    console.log('%c[sub-vue] 收到导航询问，全部完成，允许切换', 'color: #52c41a; font-weight: bold;')
    bus.$emit('navigationResponse', {
      requestId: data.requestId,
      allowed: true
    })
  }
}

// ========== eventBus 通信 ==========
const commMessage = ref('')
const receivedMessages = ref<{ from: string; content: string }[]>([])

function sendMessage() {
  if (!commMessage.value.trim()) return
  const bus = (window as any).$wujie?.bus
  if (bus) {
    bus.$emit('subMessage', {
      from: 'sub-vue',
      message: commMessage.value
    })
    commMessage.value = ''
  } else {
    console.log('[sub-vue] 不在微前端环境中，无法发送消息')
  }
}

function handleIncomingMessage(data: { from: string; message: string }) {
  receivedMessages.value.unshift({ from: data.from, content: data.message })
}

onMounted(() => {
  const bus = (window as any).$wujie?.bus
  if (bus) {
    bus.$on('subMessage', handleIncomingMessage)
    bus.$on('requestNavigation', handleNavigationRequest)
  }
})

onUnmounted(() => {
  const bus = (window as any).$wujie?.bus
  if (bus) {
    bus.$off('subMessage', handleIncomingMessage)
    bus.$off('requestNavigation', handleNavigationRequest)
  }
})
</script>
